[package]
name = "hash-table"
version = "0.2.3"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Hash Table"
license = "MIT OR Apache-2.0"

[dependencies]
siphasher = "0.2"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
